What: Emacs conference for users and developpers

When: March, 30 and 31

Where: Forward http://www.forward.co.uk/contact

Various other resources:

  - Web site:
    http://emacsconf.org

  - Mailing list:
    http://lists.hugadev.com/listinfo.cgi/emacs-conf-hugadev.com

  - Twitter account
    @EmacsConf

  - Lanyrd
    http://lanyrd.com/ckwgg

* Speakers and availabilty
** Confirmed
*** Bastien Guerry

    Org mode, or something nobody else is covering

*** Dave Snowdon

    Demonstration of how to get the best out of org mode

*** David Röthlisberger

    author of http://david.rothlis.net/emacs/howtolearn.html
    can give a basic intro to Emacs

*** Dimitri Fontaine
    el-get and Emacs Lisp Primer

*** Duncan MacGregor
    Would like to do a lightning/short talk

*** Jim Myhrberg

    Can cover Git usage via Emacs, but would give up his place for
    somebody more seasoned user who's more versed about the topic

*** Joakim Verona
    Joakim suggested:
    I presented the xwidget branch previously at a gnu hacker meeting. This
    time I would like to do it a little bit differently, to involve hackers
    rather than just present what you can do. So, more of a technical
    session where attendants are asked to compile the branch in advance and
    so on. What do you think of this?

*** Joe Corneli, All Yesterday's Tomorrows (30 minutes)

    All Yesterday's Tomorrows: The report on, and of, Project Arxana
    concerning word processing, electronic publishing, hypertext, etc.

*** John Wiegly

    I would be happy to give a presentation.  Any preferred topic ideas?

*** Luke Gorrie,  How to write an IDE like SLIME (20 minutes)

*** Nic Ferrier

    elnode

*** Ryan White

    Proposed 'Emacs from scratch', keener to see this idea presented
    rather than presenting. But can present if required.

    If this talk gets chosen, then will need to be contacted.

*** Sacha Chua

    Keynote?

*** Steve Yegge, Grok Emacs, (30 minutes to one hour)

    Well, the project is called Grok. I did a talk on it at Stanford
    recently (http://www.youtube.com/watch?v=KTJs-0EInW8), although it's
    mostly about the backend and only shows a screen shot or two of the
    Emacs client.

    The emacs mode is, of course, Grok Emacs. It's actually a minor mode
    that overlays on whatever major mode you're using. We currently
    support C++, Java, JavaScript, Python, Go, and a few internal
    languages.

    I could do a quick overview in 30 min, or a deep dive in an hour.
    I should be able to log in to work over VPN and give live demos
    of it in action.

*** Vivek Dasmohapatra
    elim
    that'll cover a few areas. Widgets. External processes.


** Maybe
*** Carl Worth (notmuch)
    The Emacs Conference does sound interesting, and I agree it would
    be worthwhile to have someone presenting on notmuch there. I'm
    currently looking into my availability, (as well as checking
    whether one of the currently most-active notmuch developers would
    be interested in speaking there).

    So let me get back to you later. And please feel free to ping me again
    if you need a reply and haven't heard from me yet.

*** Jay Belanger (calc maintainer)
    I've seen the discussion of the conference, and I wish I could be
    there. Right now it is very unlikely I'll be able to make it,
    however. (If things change and I can make it, I'd be happy to give
    a presentation.)
    Maybe something about Calc and how it interacts with other buffers

*** Magnar Sveen
    Unavailable for 7-9th March.
    Emacs Rocks talk

*** Sam Aaron Emacs Live
    Available only for 29th to 31st.
    Maybe also: Meta-eX - music with Emacs Live and Overtone

    "Energy starts surging through your fingertips. Sparks fly, making
    the shadows grow and flicker ominously around you."

    This talk will introduce Emacs Live a pack-oriented structure for
    managing your .emacs.d. Emacs Live ships with a number of optional
    packs which add extra joy to your Emacs experience:

      * Foundation Pack
      * Colour Pack
      * Clojure Pack
      * Lang Pack
      * Power Pack

    These combine to make Emacs an extremely powerful Live Coding tool
    with a specific focus on Clojure projects such as Quil and
    Overtone. However, the fun starts when you start to make your own
    packs...

** Waiting for confirmation
*** Alex Ott

    will confirm his availability at the beginning of January

** Unavailable for March

*** Xue Fuqiao
    Can't make March, but can February, July and August.

** Interactive sessions

   How to deal with the interactive sessions like these?

   We need an open space or room with table and chairs. Network would
   be a plus.

*** Hack night / hack lab
    Your head will probably be spinning with ideas from all the great
    sessions. Sit down and hack your config -- even if you've never
    touched Emacs Lisp before! This will be a working session where
    people can share what they're planning to work on (config, bugs,
    new features, whatever), congregate in appropriate groups, and
    hack away.

*** Vimgolf in Emacs
    Bring your own challenge for anyone to try to perform most
    efficiently in emacs, or replicate some of Tim Visher's: http://
    vimeo.com/timvisher/videos

*** GTD and org mode
    I will show how I take care of GTD with org-mode. (Ivan Kanis)

*** Primer in Lisp programing
    Ask me what you are trying to do with Emacs and I will show you
    how to do it with elisp. (Ivan Kanis)

** Nobody is covering

*** Beyond Emacs 24: the development roadmap
    Recently talked about on emacs development list. There is no
    roadmap. Should there be one?

*** History of Emacs told by Mr. Stallman
    Would be nice but RMS is not in Europe in March.

*** C++ programming with Emacs
    Emacs is a wonderful text editor but lacks some of the features of
    modern IDE's - specially for C++ programming. Specifically,
    Intelisense, integration with a help system and source code
    navigation are lacking. No doubt C++ notoriously complex grammar
    is partially to blame but the recent appearance of LLVM might
    provide the tools needed to solve this problem.

*** Java development in Emacs
    There are some thing I still use eclipse for: - read my maven pom
    file and use it to auto complete class names and method names -
    auto generate javadoc with @param tags - auto-refactor: rename
    methods/ classes, pulling code out into a separate method, etc -
    automatically fix some compile errors (including auto-import
    classes) - flymake style compile warnings - auto generate
    getter/setter/toString/equals All of these sound like things
    doable in emacs. would love to see how people do it. I've never
    been able to get JDEE set up

*** Python development with Emacs
    Show how to configure emacs for python development. For
    instance: - Setup auto completion (via ropemacs) - Configure emacs
    to highlight syntax errors and PEP8 violations as you code (via
    flymake) - Emacs virtualenv integration

*** Clojure development with Emacs
    Clojure is a Lisp that runs on the JVM with great support for
    concurrency and easy integration with the plethora of java
    libraries. I'd like to cover how to set up emacs as a great
    environment for cutting Clojure code.

    Emacs 24 is one of the best environment for learning Clojure and
    as Emacs configuration is Lisp then you can easily configure it
    with what you learn in Clojure. This session would help you
    establish the perfect? clojure environment using the latest
    version of Emacs, lots of great plugins for intelli-sense and REPL
    auto-completion. Clojure is much more fun with a REPL, so we will
    cover how to wire up Emacs with Leiningen 2 and also get
    auto-completion inside the REPL buffer in Emacs. We also cover
    writing your own macros to make writing Clojure even easier, eg.
    creating function definitions automagically. All the way through
    we will be learning all the relevant Emacs keyboard short-cuts
    that speedup Clojure development, eg. allow you to evaluate code
    function by function. We will even cover creating your own
    keyboard shortcuts.

** Waiting on reply (see also ivan.org)
   Sean O'Halpin
   Steve Mynott
   Thomas Koch
   Rahmu
   Dave Snowdon
   Kristian Hellquist
   Johan Andersson
   Jim Crossley
   Charles Turner


** Book raffle

   http://emacsconf.org/proposals/34

   suggested by mhuber of Linux Magazine, Germany

   One issue I see with this, is when the publishers send over titles,
   the customs hold them up sometimes even thought they are marked as
   'gifts'.
