* Speakers and availabilty

** Waiting on reply
*** Sean O'Halpin
*** Steve Mynott
*** Thomas Koch
*** Ryan Davis
*** Rahmu
*** Dave Snowdon
*** Kristian Hellquist
*** Johan Andersson
*** Jim Crossley
*** Duncan MacGregor
*** Paul Butcher
*** Charles Turner
*** Ryan White

** Good for March
*** Nic Ferrier
    el-node

*** Sacha Chua
    Keynote?

*** Dimitri Fontaine
    - el-get
    - Emacs Lisp Primer

*** Bastien
    Org mode, or something nobody else is covering

*** Jim Myhrberg
    Can cover Git usage via Emacs, but would give up his place for
    somebody more seasoned user who's more versed about the topic

*** David Röthlisberger
    author of http://david.rothlis.net/emacs/howtolearn.html
    can give a basic intro to Emacs


** Some dates in March unavailable for
*** Ivan Kanis
    Can't make 2nd March.
    Org mode with Getting Things Done.

*** Magnar Sveen
    Unavailable for 7-9th March.
    Emacs Rocks talk

*** Sam Aaron
    Available only for 29th to 31st.
    Emacs Live http://emacsconf.org/proposals/45
    Maybe also: Meta-eX - music with Emacs Live and Overtone

** Waiting for confirmation
*** Joakim Verona
    isn't sure about his availability, waiting for confirmation

*** Alex Ott
    will confirm his availability at the beginning of January


** Unavailable for March
*** Xue Fuqiao
    Can't make March, but can February, July and August.


** Maybe duplicate
*** Dave Snowdon Org mode http://emacsconf.org/proposals/4

** Interactive sessions

   How to deal with the interactive sessions like these?

   http://emacsconf.org/proposals/41
   http://emacsconf.org/proposals/43
   http://emacsconf.org/proposals/44
   http://emacsconf.org/proposals/46
   http://emacsconf.org/proposals/47

** Nobody is covering

   * "Beyond Emacs 24: the development roadmap"
   http://emacsconf.org/proposals/24

   * History of Emacs told by Mr. Stallman
   http://emacsconf.org/proposals/50

** How to deal with

   Set up/use Emacs for $LANGUAGE ?
   http://emacsconf.org/proposals/15
   http://emacsconf.org/proposals/20
   http://emacsconf.org/proposals/30
   http://emacsconf.org/proposals/33
   http://emacsconf.org/proposals/34

   As in, what format should it be? What if some attendees arent
   interested in the config for a $LANGUAGE? How do you balance this
   out?

** Book raffle

   http://emacsconf.org/proposals/34

   suggested by mhuber of Linux Magazine, Germany

   One issue I see with this, is when the publishers send over titles,
   the customs hold them up sometimes even thought they are marked as
   'gifts'.
